site_name: Nathan Hadley Portfolio
docs_dir: docs
site_dir: site

nav:
  - Home: README.md
  - API Docs:
      - Overview: API-Docs/README.md
      - NASA APOD API: API-Docs/NASA-APOD-API.md
      - ISS Location API: API-Docs/ISS-Location-API.md
      - JSONPlaceholder POST: API-Docs/JSONPlaceholder-POST-API.md
      - JSONPlaceholder PUT: API-Docs/JSONPlaceholder-PUT-API.md
      - JSONPlaceholder DELETE: API-Docs/JSONPlaceHolder-DELETE-API.md

  - Case Studies: 
      - Overview: Case Studies/README.md
      - BPM: Case Studies/VDartDigital-BPM.pdf
      - Data Analytics: Case Studies/VDartDigital-Data Analytics.pdf
      - Forge Rock: Case Studies/VDartDigital-ForgeRock.pdf
      - VGI: Case Studies/VDartDigital-VGI.pdf
      
  - Video Tutorials: 
      - BloFin 2FA:  Video-Tutorials//Blofin-2FA.mp4
  
  - eBooks: eBooks/README.md
theme:
  name: material
