site_name: Nathan Hadley Portfolio
docs_dir: docs
site_dir: site

nav:
  - Home: README.md
  - API Docs:
      - Overview: API-Docs/README.md
      - NASA APOD API: API-Docs/NASA-APOD-API.md
      - ISS Location API: API-Docs/ISS-Location-API.md
      - JSONPlaceholder POST: API-Docs/JSONPlaceholder-POST-API.md
      - JSONPlaceholder PUT: API-Docs/JSONPlaceholder-PUT-API.md
      - JSONPlaceholder DELETE: API-Docs/JSONPlaceHolder-DELETE-API.md

  - Case Studies: 
      - Overview: Case Studies/README.md
      - BPM: Case Studies/VDartDigital-BPM.pdf
      - Data Analytics: Case Studies/VDartDigital-Data Analytics.pdf
      - Forge Rock: Case Studies/VDartDigital-ForgeRock.pdf
      - VGI: Case Studies/VDartDigital-VGI.pdf
      
  - Video Tutorials: 
      - Overview: Video-Tutorials/README.md
      - Collier Aerospace: Video-Tutorials/Collier_Aerospace.md
  
  - eBooks: eBooks/README.md
      - Overview: eBooks/README.md
      - Cloud Computing: eBooks/Cloud computing.pdf
      - IoT: eBooks/IOT ebook.pdf
      - Managing Digital Identities: eBooks/Managing Digital Identities.pdf
      - RPA: ebooks/RPA EBOOK.pdf
      
theme:
  name: material
